### ISSUE TITLE
프로젝트 배포 여부에 따라 바뀌어야 하는 부분

### ISSUE THREAD

**Issue by yusungsim** [hermioneee2/mini-memo#9]
* Naver API 용 주소 부분

naver api에서 신청을 다시해서 코드를 수정하면 되는데, 저희 프로젝트가 배포를 해야하는지 명확하지 않아 우선 localhost:3000으로 했습니다. 코드상에서 링크만 변경하면 되는 것은 아니지만 수정은 가능해요.

_Originally posted by @hermioneee2 in https://github.com/hermioneee2/mini-memo/pull/7#discussion_r754094077_

**Comment by hermioneee2** [comment]
저희 프로젝트가 배포를 하지 않아도 된다고 하여 localhost:3000으로 변경없이 제출해도 좋을 것 같습니다.
